version: '3.3'

services:
  authelia:
    image: authelia/authelia
    container_name: authelia
    volumes:
      - ./config:/config
      - ./log:/var/log
    networks:
      - ${NETWORK_NAME}
    expose:
      - 9091
    restart: unless-stopped
    healthcheck:
      disable: true
    environment:
      - TZ=Europe/Berlin

  proxy:
    hostname: proxy_authelia
    image: lscr.io/linuxserver/nginx:latest
    container_name: proxy_authelia
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - ./nginx-config:/config
      - ./letsencrypt:/etc/letsencrypt
    networks:
      - ${NETWORK_NAME}

networks:
  ${NETWORK_NAME}:
    external: true
