---
###############################################################
#                   Authelia configuration                    #
###############################################################

jwt_secret: a_very_important_secret
default_redirection_url: https://authelia.domain.com/

server:
  host: 0.0.0.0
  port: 9091

log:
  level: debug
  format: text
  file_path: /var/log/authelia.log

totp:
  issuer: authelia.com

authentication_backend:
  file:
    path: /config/users_database.yml

access_control:
  default_policy: deny
  rules:
    - domain: 2factor.domain.com
      policy: two_factor
      subject:
      - ['user:username']
session:
  domain: domain.com
  name: authelia_session
#  same_site: lax
#  secret: unsecure_session_secret
#  expiration: 1h
#  inactivity: 5m
  remember_me_duration: -1

regulation:
  max_retries: 3
  find_time: 120
  ban_time: 300

storage:
  encryption_key: you_must_generate_a_random_string_of_more_than_twenty_chars_and_configure_this
  local:
    path: /config/db.sqlite3

notifier:
  filesystem:
    filename: /config/notification.txt
...
